services:
  doctor-ui:
    build:
      context: DoctorUI
      dockerfile: DoctorUI/Dockerfile
    ports:
      - 8060:80

  patient-ui:
    build:
      context: PatientUI
      dockerfile: PatientUI/Dockerfile
    ports:
      - 8070:80
  
  measurement-service:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports:
      - 8080:8080
      
  patient-service:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - 8090:8080
      
  measurementsDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1443:1433

  patientsDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1433:1433
    
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
    
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage

  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - 3306:3306
    volumes:
      - zipkin_data:/mysql/data
volumes:
  rps_seq_data:
  zipkin_data: